# Generated by Django 4.2.26 on 2025-12-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('vaccination', 'Вакцинация'), ('diagnosis', 'Диагноз'), ('procedure', 'Процедура'), ('lab_test', 'Лабораторный анализ'), ('medication', 'Назначение лекарств'), ('note', 'Заметка'), ('surgery', 'Операция')], max_length=20, verbose_name='Тип записи')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата события')),
                ('document', models.FileField(blank=True, help_text='Опционально: фото чека, анализа, сертификата и т.д.', null=True, upload_to='medical_records/', verbose_name='Документ (PDF, фото)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Медицинская запись',
                'verbose_name_plural': 'Медицинские записи',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
