# Generated by Django 6.0.4 on 2026-04-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pets/photos/', verbose_name='Фото питомца'),
        ),
    ]
