# Generated by Django 4.2.26 on 2025-12-17 08:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='admins',
            field=models.ManyToManyField(limit_choices_to={'user_type__in': ['clinic_admin', 'vet']}, related_name='managed_clinics', to=settings.AUTH_USER_MODEL, verbose_name='Администраторы'),
        ),
    ]
