# Generated by Django 4.2.26 on 2025-12-18 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinics', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (руб.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clinics.clinic', verbose_name='Клиника')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_slots', models.JSONField(default=list, verbose_name='Доступные слоты')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='services.service')),
                ('vet', models.ForeignKey(limit_choices_to={'user_type__in': ['vet', 'clinic_admin']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ветеринар')),
            ],
            options={
                'verbose_name': 'Назначение услуги',
                'verbose_name_plural': 'Назначения услуг',
                'unique_together': {('service', 'vet')},
            },
        ),
    ]
